name: invoice_sorter
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  ffigen: ^7.2.6
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

ffigen:
  name: PdfIo
  output: lib/utils/libpdfio.dart
  headers:
    entry-points:
      - "src/pdfio-1.1.0/pdfio.h"
